apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./php/CVE-2024-2961/docker-compose.yml.backup -o vul_app/php/CVE-2024-2961/cve-2024-2961.yaml --volumes hostPath
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cve-2024-2961-web
  name: cve-2024-2961-web
  namespace: metarget
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-2024-2961-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./php/CVE-2024-2961/docker-compose.yml.backup -o vul_app/php/CVE-2024-2961/cve-2024-2961.yaml --volumes hostPath
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cve-2024-2961-web
    spec:
      containers:
        - image: vulhub/cve-2024-2961-php:8.3.4-apache
          name: cve-2024-2961-web
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/
              name: cve-2024-2961-web-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: php/CVE-2024-2961/www
          name: cve-2024-2961-web-hostpath0

