apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./php/CVE-2024-2961/docker-compose.yml.backup -o vul_app/php/CVE-2024-2961/cve-2024-2961.yaml --volumes hostPath
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cve-2024-2961-web
  name: cve-2024-2961-web
  namespace: metarget
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: cve-2024-2961-web
